using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Input;
using System.Windows.Threading;
using ClipNotes.Helpers;
using ClipNotes.Models;
using ClipNotes.Services;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using LogSvc = ClipNotes.Services.LogService;
using Loc = ClipNotes.Helpers.LocalizationService;

namespace ClipNotes.ViewModels;

public partial class MainViewModel : ObservableObject
{
    private readonly ObsWebSocketService _obs;
    private readonly FFmpegService _ffmpeg;
    private readonly WhisperService _whisper;
    private readonly ExcelService _excel;
    private readonly SessionService _sessionService;
    private readonly SettingsService _settingsService;
    private readonly HotkeyService _hotkeyService;
    private readonly DispatcherTimer _recordingTimer;
    private CancellationTokenSource? _pipelineCts;

    // Current session
    private SessionData? _currentSession;
    private bool _sessionNameWasAutoGenerated;

    // --- Navigation ---
    [ObservableProperty] private int _currentTab; // 0=Запись, 1=Экспорт, 2=История, 3=Настройки

    // --- Setup fields ---
    [ObservableProperty] private string _obsHost = "localhost";
    [ObservableProperty] private int _obsPort = 4455;
    [ObservableProperty] private string _obsPassword = "";
    [ObservableProperty] private bool _obsConnected;
    [ObservableProperty] private string _obsStatus = "";
    [ObservableProperty] private string _outputRootDirectory = "";
    [ObservableProperty] private double _preSeconds = 5.0;
    [ObservableProperty] private double _postSeconds = 5.0;
    [ObservableProperty] private string _audioCodec = "wav";
    [ObservableProperty] private int _audioBitrate = 192;
    [ObservableProperty] private string _whisperModel = "large-v3-turbo";
    [ObservableProperty] private string _transcriptionLanguage = "auto";
    [ObservableProperty] private string _glossary = "";
    [ObservableProperty] private string? _glossaryFilePath;
    public ObservableCollection<HotkeyBinding> HotkeyBindings { get; } = new();

    // --- Custom output paths ---
    [ObservableProperty] private bool _useCustomVideoPath;
    [ObservableProperty] private string _customVideoPath = "";
    [ObservableProperty] private bool _videoPathCopy;
    [ObservableProperty] private bool _useCustomAudioPath;
    [ObservableProperty] private string _customAudioPath = "";
    [ObservableProperty] private bool _audioPathCopy;
    [ObservableProperty] private bool _useCustomTxtPath;
    [ObservableProperty] private string _customTxtPath = "";
    [ObservableProperty] private bool _txtPathCopy;
    [ObservableProperty] private bool _useCustomTablePath;
    [ObservableProperty] private string _customTablePath = "";
    [ObservableProperty] private bool _tablePathCopy;

    // --- Session naming ---
    [ObservableProperty] private string _sessionName = "";
    [ObservableProperty] private bool _askSessionName = true;
    [ObservableProperty] private bool _appendDateSuffix = false;
    [ObservableProperty] private string _dateSuffixFormat = "_{dd}.{mm}";

    // --- Recording fields ---
    [ObservableProperty] private bool _isRecording;
    [ObservableProperty] private string _recordingTime = "00:00:00";
    [ObservableProperty] private string _recordingStatus = "";
    public ObservableCollection<Marker> Markers { get; } = new();
    public string MarkersCountLabel => string.Format(Loc.T("loc_MarkersCount"), Markers.Count);

    // --- Review fields ---
    [ObservableProperty] private bool _isProcessing;
    [ObservableProperty] private string _processingStatus = "";
    [ObservableProperty] private int _processingProgress;
    [ObservableProperty] private int _processingTotal = 1;
    [ObservableProperty] private bool _reviewReady;

    // --- Manual video loading (without OBS) ---
    [ObservableProperty] private string? _loadedVideoPath;
    [ObservableProperty] private string _manualMarkerTimecode = "00:00:30";
    [ObservableProperty] private MarkerType _manualMarkerType = MarkerType.Note;

    // --- OBS auto-start ---
    [ObservableProperty] private bool _autoStartObs;
    [ObservableProperty] private string _obsExePath = "";

    // --- Tray / startup ---
    [ObservableProperty] private bool _startWithWindows;
    [ObservableProperty] private bool _minimizeToTray;

    // --- Hold mode ---
    [ObservableProperty] private bool _holdModeEnabled;
    [ObservableProperty] private double _holdPreSeconds = 2.0;
    [ObservableProperty] private double _holdPostSeconds = 2.0;

    // Hold state (runtime)
    private TimeSpan? _holdStart;
    private MarkerType _holdMarkerType;

    // Hold visual indicator
    [ObservableProperty] private bool _isHolding;
    [ObservableProperty] private MarkerType _holdingType;
    [ObservableProperty] private string _holdingTimerText = "0.0";
    private DateTime _holdStartWallClock;
    private readonly DispatcherTimer _holdTimer;

    // --- Tool validation ---
    [ObservableProperty] private string _toolsStatus = "";

    // --- Logs ---
    [ObservableProperty] private string _logText = "";

    // --- History ---
    public ObservableCollection<SessionHistoryEntry> SessionHistory { get; } = new();
    [ObservableProperty] private int _maxHistoryCount = 20;
    [ObservableProperty] private bool _deleteFilesOnClear;
    [ObservableProperty] private bool _clearMarkersOnVideoLoad = true;

    // --- Theme ---
    [ObservableProperty] private int _selectedThemeIndex; // 0=Light, 1=Dark
    private bool _themeSetByUser;
    private bool _settingsLoaded;

    // --- Updates ---
    [ObservableProperty] private string _updateStatus = "";
    [ObservableProperty] private bool _isCheckingUpdate;
    [ObservableProperty] private bool _updateAvailable;
    [ObservableProperty] private string? _updateUrl;
    // Stored hash of the installed bundle ZIP — used to detect silent content changes.
    [ObservableProperty] private string? _installedBundleHash;
    // Download + staging state (not persisted)
    [ObservableProperty] private bool _isDownloadingUpdate;
    [ObservableProperty] private bool _isUpdateReady;   // true after bundle staged successfully
    private string? _latestVersionForDialog;
    private string? _pendingStagingDir;
    private string? _pendingUpdaterScript;

    // --- Language ---
    [ObservableProperty] private string _selectedLanguage = "ru";
    public List<string> AvailableLanguages { get; private set; } = [];

    // --- Audio codec options ---
    public string[] AudioCodecOptions { get; } = { "wav", "mp3", "aac" };
    public ModelOption[] ModelOptions { get; } =
    {
        new("large-v3-turbo", "large-v3-turbo — ~6 GB VRAM"),
        new("large-v3",       "large-v3 — ~10 GB VRAM"),
        new("medium",         "medium — ~5 GB VRAM"),
        new("small",          "small — ~2 GB VRAM"),
        new("base",           "base — ~1 GB VRAM"),
    };
    public string[] LanguageOptions { get; } = { "auto", "ru", "en", "de", "fr", "es", "zh", "ja", "ko" };
    public MarkerType[] MarkerTypeOptions { get; } = { MarkerType.Bug, MarkerType.Task, MarkerType.Note, MarkerType.Summary };

    public MainViewModel()
    {
        _obs = new ObsWebSocketService();
        _ffmpeg = new FFmpegService();
        _whisper = new WhisperService();
        _excel = new ExcelService();
        _sessionService = new SessionService();
        _settingsService = new SettingsService();
        _hotkeyService = new HotkeyService();

        _recordingTimer = new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(500) };
        _recordingTimer.Tick += OnRecordingTimerTick;

        _holdTimer = new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(100) };
        _holdTimer.Tick += (_, _) =>
        {
            var elapsed = DateTime.Now - _holdStartWallClock;
            HoldingTimerText = $"{elapsed.TotalSeconds:F1}";
        };

        _obs.RecordStateChanged += OnRecordStateChanged;
        _obs.RecordStopped += OnRecordStopped;
        _obs.Error += msg =>
        {
            LogSvc.Error($"OBS: {msg}");
            Application.Current?.Dispatcher.Invoke(() => ObsStatus = $"{Loc.T("loc_StatusObsError")}: {msg}");
        };

        _hotkeyService.HotkeyPressed += OnHotkeyPressed;
        _hotkeyService.HotkeyReleased += OnHotkeyReleased;

        Markers.CollectionChanged += (_, _) => OnPropertyChanged(nameof(MarkersCountLabel));

        // Subscribe to new log entries; today's log file is loaded later via InitializeLogs()
        LogSvc.LogEntryAdded += OnLogEntryAdded;

        AvailableLanguages = Loc.GetAvailableLanguages();
        LoadSettings();
        SetupToolPaths();
        ValidateTools();

        // Автозапуск OBS.exe если включено — validate extension to prevent launching arbitrary files.
        if (AutoStartObs && File.Exists(ObsExePath)
            && string.Equals(Path.GetExtension(ObsExePath), ".exe", StringComparison.OrdinalIgnoreCase))
            Process.Start(new ProcessStartInfo(ObsExePath) { UseShellExecute = true });

        // Авто-подключение OBS если настройки заполнены
        if (!string.IsNullOrWhiteSpace(ObsHost) && ObsPort > 0)
            Task.Run(() => _ = TestObsConnectionAsync());
    }

    private void SetupToolPaths()
    {
        _ffmpeg.SetPaths(PathHelper.FFmpegPath, PathHelper.FFprobePath);
        _whisper.SetPaths(PathHelper.WhisperCliPath, PathHelper.GetModelPath(WhisperModel));
    }

    private void ValidateTools()
    {
        var missing = Loc.T("loc_StatusToolsMissing");
        var issues = new List<string>();
        if (!File.Exists(PathHelper.FFmpegPath)) issues.Add($"ffmpeg.exe {missing}");
        if (!File.Exists(PathHelper.FFprobePath)) issues.Add($"ffprobe.exe {missing}");
        if (!File.Exists(PathHelper.WhisperCliPath)) issues.Add($"whisper-cli.exe {missing}");

        var modelPath = PathHelper.GetModelPath(WhisperModel);
        if (!File.Exists(modelPath))
            issues.Add($"'{WhisperModel}' {Loc.T("loc_StatusModelMissing")}");

        ToolsStatus = issues.Count == 0
            ? $"{Loc.T("loc_StatusToolsOk")}: {WhisperModel}"
            : "[!] " + string.Join("; ", issues);
    }

    private static int DetectWindowsTheme()
    {
        try
        {
            using var key = Microsoft.Win32.Registry.CurrentUser.OpenSubKey(
                @"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize");
            if (key?.GetValue("AppsUseLightTheme") is int v && v == 0)
                return 1; // Dark
        }
        catch (Exception) { } // Registry unavailable — default to Light
        return 0; // Light
    }

    partial void OnWhisperModelChanged(string value)
    {
        SetupToolPaths();
        ValidateTools();
    }

    public void Cleanup()
    {
        LogSvc.LogEntryAdded -= OnLogEntryAdded;
        _recordingTimer.Stop();
        _hotkeyService.Dispose();
        _obs.Dispose();
        SaveSettings();
        // Clean up any staged update that was dismissed with "Later"
        if (!IsUpdateReady)
            UpdateService.CleanupStagedUpdate(_pendingStagingDir, _pendingUpdaterScript);
    }
}

public record ModelOption(string Value, string Display)
{
    public override string ToString() => Display;
    public string ModelName => Display.Contains(" — ") ? Display[..Display.IndexOf(" — ")] : Display;
    public string VramHint  => Display.Contains(" — ") ? Display[(Display.IndexOf(" — ") + 3)..] : "";
}
