using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Input;
using System.Windows.Threading;
using ClipNotes.Helpers;
using ClipNotes.Models;
using ClipNotes.Services;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using LogSvc = ClipNotes.Services.LogService;
using Loc = ClipNotes.Helpers.LocalizationService;

namespace ClipNotes.ViewModels;

public partial class MainViewModel : ObservableObject
{
    private readonly ObsWebSocketService _obs;
    private readonly FFmpegService _ffmpeg;
    private readonly WhisperService _whisper;
    private readonly ExcelService _excel;
    private readonly SessionService _sessionService;
    private readonly SettingsService _settingsService;
    private readonly HotkeyService _hotkeyService;
    private readonly DispatcherTimer _recordingTimer;
    private CancellationTokenSource? _pipelineCts;

    // Current session
    private SessionData? _currentSession;
    private bool _sessionNameWasAutoGenerated;

    // --- Navigation ---
    [ObservableProperty] private int _currentTab; // 0=Запись, 1=Экспорт, 2=История, 3=Настройки

    // --- Setup fields ---
    [ObservableProperty] private string _obsHost = "localhost";
    [ObservableProperty] private int _obsPort = 4455;
    [ObservableProperty] private string _obsPassword = "";
    [ObservableProperty] private bool _obsConnected;
    [ObservableProperty] private string _obsStatus = "";
    [ObservableProperty] private string _outputRootDirectory = "";
    [ObservableProperty] private double _preSeconds = 5.0;
    [ObservableProperty] private double _postSeconds = 5.0;
    [ObservableProperty] private string _audioCodec = "wav";
    [ObservableProperty] private int _audioBitrate = 192;
    [ObservableProperty] private string _whisperModel = "large-v3-turbo";
    [ObservableProperty] private string _transcriptionLanguage = "auto";
    [ObservableProperty] private string _glossary = "";
    [ObservableProperty] private string? _glossaryFilePath;
    public ObservableCollection<HotkeyBinding> HotkeyBindings { get; } = new();

    // --- Custom output paths ---
    [ObservableProperty] private bool _useCustomVideoPath;
    [ObservableProperty] private string _customVideoPath = "";
    [ObservableProperty] private bool _videoPathCopy;
    [ObservableProperty] private bool _useCustomAudioPath;
    [ObservableProperty] private string _customAudioPath = "";
    [ObservableProperty] private bool _audioPathCopy;
    [ObservableProperty] private bool _useCustomTxtPath;
    [ObservableProperty] private string _customTxtPath = "";
    [ObservableProperty] private bool _txtPathCopy;
    [ObservableProperty] private bool _useCustomTablePath;
    [ObservableProperty] private string _customTablePath = "";
    [ObservableProperty] private bool _tablePathCopy;

    // --- Session naming ---
    [ObservableProperty] private string _sessionName = "";
    [ObservableProperty] private bool _askSessionName = true;
    [ObservableProperty] private bool _appendDateSuffix = false;
    [ObservableProperty] private string _dateSuffixFormat = "_{dd}.{mm}";

    // --- Recording fields ---
    [ObservableProperty] private bool _isRecording;
    [ObservableProperty] private string _recordingTime = "00:00:00";
    [ObservableProperty] private string _recordingStatus = "";
    public ObservableCollection<Marker> Markers { get; } = new();
    public string MarkersCountLabel => string.Format(Loc.T("loc_MarkersCount"), Markers.Count);

    // --- Review fields ---
    [ObservableProperty] private bool _isProcessing;
    [ObservableProperty] private string _processingStatus = "";
    [ObservableProperty] private int _processingProgress;
    [ObservableProperty] private int _processingTotal = 1;
    [ObservableProperty] private bool _reviewReady;

    // --- Manual video loading (without OBS) ---
    [ObservableProperty] private string? _loadedVideoPath;
    [ObservableProperty] private string _manualMarkerTimecode = "00:00:30";
    [ObservableProperty] private MarkerType _manualMarkerType = MarkerType.Note;

    // --- OBS auto-start ---
    [ObservableProperty] private bool _autoStartObs;
    [ObservableProperty] private string _obsExePath = "";

    // --- Tray / startup ---
    [ObservableProperty] private bool _startWithWindows;
    [ObservableProperty] private bool _minimizeToTray;

    // --- Hold mode ---
    [ObservableProperty] private bool _holdModeEnabled;
    [ObservableProperty] private double _holdPreSeconds = 2.0;
    [ObservableProperty] private double _holdPostSeconds = 2.0;

    // Hold state (runtime)
    private TimeSpan? _holdStart;
    private MarkerType _holdMarkerType;

    // Hold visual indicator
    [ObservableProperty] private bool _isHolding;
    [ObservableProperty] private MarkerType _holdingType;
    [ObservableProperty] private string _holdingTimerText = "0.0";
    private DateTime _holdStartWallClock;
    private readonly DispatcherTimer _holdTimer;

    // --- Tool validation ---
    [ObservableProperty] private string _toolsStatus = "";

    // --- Logs ---
    [ObservableProperty] private string _logText = "";

    // --- History ---
    public ObservableCollection<SessionHistoryEntry> SessionHistory { get; } = new();
    [ObservableProperty] private int _maxHistoryCount = 20;
    [ObservableProperty] private bool _deleteFilesOnClear;
    [ObservableProperty] private bool _clearMarkersOnVideoLoad = true;

    // --- Theme ---
    [ObservableProperty] private int _selectedThemeIndex; // 0=Light, 1=Dark
    private bool _themeSetByUser;
    private bool _settingsLoaded;

    // --- Language ---
    [ObservableProperty] private string _selectedLanguage = "ru";
    public List<string> AvailableLanguages { get; private set; } = [];

    partial void OnSelectedLanguageChanged(string value)
    {
        Loc.Load(value);
        foreach (var hk in HotkeyBindings)
            hk.NotifyLocalizationChanged();
        // Refresh status strings that are set in code
        if (!IsRecording && !IsProcessing)
        {
            if (!ObsConnected) ObsStatus = Loc.T("loc_StatusObsDisconnected");
            RecordingStatus = Loc.T("loc_StatusReady");
        }
        OnPropertyChanged(nameof(MarkersCountLabel));
        ValidateTools();
        SaveSettings();
    }

    partial void OnSelectedThemeIndexChanged(int value)
    {
        App.ApplyTheme(value == 1);
        if (_settingsLoaded) _themeSetByUser = true;
        SaveSettings();
    }

    private static int DetectWindowsTheme()
    {
        try
        {
            using var key = Microsoft.Win32.Registry.CurrentUser.OpenSubKey(
                @"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize");
            if (key?.GetValue("AppsUseLightTheme") is int v && v == 0)
                return 1; // Dark
        }
        catch { }
        return 0; // Light
    }

    // --- Audio codec options ---
    public string[] AudioCodecOptions { get; } = { "wav", "mp3", "aac" };
    public ModelOption[] ModelOptions { get; } =
    {
        new("large-v3-turbo", "large-v3-turbo — ~6 GB VRAM"),
        new("large-v3",       "large-v3 — ~10 GB VRAM"),
        new("medium",         "medium — ~5 GB VRAM"),
        new("small",          "small — ~2 GB VRAM"),
        new("base",           "base — ~1 GB VRAM"),
    };
    public string[] LanguageOptions { get; } = { "auto", "ru", "en", "de", "fr", "es", "zh", "ja", "ko" };
    public MarkerType[] MarkerTypeOptions { get; } = { MarkerType.Bug, MarkerType.Task, MarkerType.Note, MarkerType.Summary };

    public MainViewModel()
    {
        _obs = new ObsWebSocketService();
        _ffmpeg = new FFmpegService();
        _whisper = new WhisperService();
        _excel = new ExcelService();
        _sessionService = new SessionService();
        _settingsService = new SettingsService();
        _hotkeyService = new HotkeyService();

        _recordingTimer = new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(500) };
        _recordingTimer.Tick += OnRecordingTimerTick;

        _holdTimer = new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(100) };
        _holdTimer.Tick += (_, _) =>
        {
            var elapsed = DateTime.Now - _holdStartWallClock;
            HoldingTimerText = $"{elapsed.TotalSeconds:F1}";
        };

        _obs.RecordStateChanged += OnRecordStateChanged;
        _obs.RecordStopped += OnRecordStopped;
        _obs.Error += msg =>
        {
            LogSvc.Error($"OBS: {msg}");
            Application.Current?.Dispatcher.Invoke(() => ObsStatus = $"{Loc.T("loc_StatusObsError")}: {msg}");
        };

        _hotkeyService.HotkeyPressed += OnHotkeyPressed;
        _hotkeyService.HotkeyReleased += OnHotkeyReleased;

        Markers.CollectionChanged += (_, _) => OnPropertyChanged(nameof(MarkersCountLabel));

        // Load today's existing log file into buffer, then subscribe to new entries
        var todayLog = Path.Combine(LogSvc.LogDir, $"{DateTime.Now:yyyy-MM-dd}.log");
        if (File.Exists(todayLog))
        {
            try { _logText = File.ReadAllText(todayLog).TrimEnd(); } catch { }
        }
        LogSvc.LogEntryAdded += OnLogEntryAdded;

        AvailableLanguages = Loc.GetAvailableLanguages();
        LoadSettings();
        SetupToolPaths();
        ValidateTools();

        // Автозапуск OBS.exe если включено
        if (AutoStartObs && File.Exists(ObsExePath))
            System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(ObsExePath) { UseShellExecute = true });

        // Авто-подключение OBS если настройки заполнены
        if (!string.IsNullOrWhiteSpace(ObsHost) && ObsPort > 0)
            Task.Run(() => _ = TestObsConnectionAsync());
    }

    private void SetupToolPaths()
    {
        _ffmpeg.SetPaths(PathHelper.FFmpegPath, PathHelper.FFprobePath);
        _whisper.SetPaths(PathHelper.WhisperCliPath, PathHelper.GetModelPath(WhisperModel));
    }

    private void ValidateTools()
    {
        var missing = Loc.T("loc_StatusToolsMissing");
        var issues = new List<string>();
        if (!File.Exists(PathHelper.FFmpegPath)) issues.Add($"ffmpeg.exe {missing}");
        if (!File.Exists(PathHelper.FFprobePath)) issues.Add($"ffprobe.exe {missing}");
        if (!File.Exists(PathHelper.WhisperCliPath)) issues.Add($"whisper-cli.exe {missing}");

        var modelPath = PathHelper.GetModelPath(WhisperModel);
        if (!File.Exists(modelPath))
            issues.Add($"'{WhisperModel}' {Loc.T("loc_StatusModelMissing")}");

        ToolsStatus = issues.Count == 0
            ? $"{Loc.T("loc_StatusToolsOk")}: {WhisperModel}"
            : "⚠ " + string.Join("; ", issues);
    }

    partial void OnWhisperModelChanged(string value)
    {
        SetupToolPaths();
        ValidateTools();
    }

    partial void OnAutoStartObsChanged(bool value) => SaveSettings();

    partial void OnMinimizeToTrayChanged(bool value) => SaveSettings();

    partial void OnClearMarkersOnVideoLoadChanged(bool value) => SaveSettings();

    partial void OnHoldModeEnabledChanged(bool value)
    {
        if (value) _hotkeyService.EnableHoldMode();
        else _hotkeyService.DisableHoldMode();
        SaveSettings();
    }

    partial void OnHoldPreSecondsChanged(double value) => SaveSettings();
    partial void OnHoldPostSecondsChanged(double value) => SaveSettings();

    partial void OnUseCustomVideoPathChanged(bool value) => SaveSettings();
    partial void OnCustomVideoPathChanged(string value) => SaveSettings();
    partial void OnVideoPathCopyChanged(bool value) => SaveSettings();
    partial void OnAudioPathCopyChanged(bool value) => SaveSettings();
    partial void OnTxtPathCopyChanged(bool value) => SaveSettings();
    partial void OnTablePathCopyChanged(bool value) => SaveSettings();
    partial void OnUseCustomAudioPathChanged(bool value) => SaveSettings();
    partial void OnCustomAudioPathChanged(string value) => SaveSettings();
    partial void OnUseCustomTxtPathChanged(bool value) => SaveSettings();
    partial void OnCustomTxtPathChanged(string value) => SaveSettings();
    partial void OnUseCustomTablePathChanged(bool value) => SaveSettings();
    partial void OnCustomTablePathChanged(string value) => SaveSettings();

    partial void OnAskSessionNameChanged(bool value) => SaveSettings();
    partial void OnAppendDateSuffixChanged(bool value) => SaveSettings();
    partial void OnDateSuffixFormatChanged(string value) => SaveSettings();

    partial void OnStartWithWindowsChanged(bool value)
    {
        try
        {
            using var key = Microsoft.Win32.Registry.CurrentUser.OpenSubKey(
                @"SOFTWARE\Microsoft\Windows\CurrentVersion\Run", true);
            var exePath = Process.GetCurrentProcess().MainModule?.FileName ?? "";
            if (value)
                key?.SetValue("ClipNotes", $"\"{exePath}\" --tray");
            else
                key?.DeleteValue("ClipNotes", false);
        }
        catch (Exception ex) { LogSvc.Warn($"Registry error: {ex.Message}"); }
        SaveSettings();
    }

    private void LoadSettings()
    {
        var s = _settingsService.Load();
        ObsHost = s.ObsHost;
        ObsPort = s.ObsPort;
        ObsPassword = s.ObsPassword ?? "";
        OutputRootDirectory = s.OutputRootDirectory;
        PreSeconds = s.PreSeconds;
        PostSeconds = s.PostSeconds;
        AudioCodec = s.AudioCodec;
        AudioBitrate = s.AudioBitrate;
        WhisperModel = s.WhisperModel;
        TranscriptionLanguage = s.TranscriptionLanguage;
        Glossary = s.Glossary;
        GlossaryFilePath = s.GlossaryFilePath;

        HotkeyBindings.Clear();
        foreach (var hk in s.Hotkeys)
        {
            HotkeyBindings.Add(new HotkeyBinding
            {
                Action = hk.Action,
                Key = (Key)hk.Key,
                Modifiers = (ModifierKeys)hk.Modifiers
            });
        }

        // Ensure all actions have bindings
        foreach (var action in Enum.GetValues<HotkeyAction>())
        {
            if (!HotkeyBindings.Any(h => h.Action == action))
                HotkeyBindings.Add(new HotkeyBinding { Action = action });
        }

        SessionHistory.Clear();
        MaxHistoryCount = s.MaxHistoryCount;
        foreach (var h in s.SessionHistory.OrderByDescending(x => x.CreatedAt).Take(MaxHistoryCount))
            SessionHistory.Add(h);

        AutoStartObs = s.AutoStartObs;
        ObsExePath = s.ObsExePath;
        StartWithWindows = s.StartWithWindows;
        MinimizeToTray = s.MinimizeToTray;
        DeleteFilesOnClear = s.DeleteFilesOnClear;
        ClearMarkersOnVideoLoad = s.ClearMarkersOnVideoLoad;
        UseCustomVideoPath = s.UseCustomVideoPath;
        CustomVideoPath = s.CustomVideoPath;
        VideoPathCopy = s.VideoPathCopy;
        UseCustomAudioPath = s.UseCustomAudioPath;
        CustomAudioPath = s.CustomAudioPath;
        AudioPathCopy = s.AudioPathCopy;
        UseCustomTxtPath = s.UseCustomTxtPath;
        CustomTxtPath = s.CustomTxtPath;
        TxtPathCopy = s.TxtPathCopy;
        UseCustomTablePath = s.UseCustomTablePath;
        CustomTablePath = s.CustomTablePath;
        TablePathCopy = s.TablePathCopy;
        AskSessionName = s.AskSessionName;
        AppendDateSuffix = s.AppendDateSuffix;
        DateSuffixFormat = s.DateSuffixFormat;
        HoldPreSeconds = s.HoldPreSeconds;
        HoldPostSeconds = s.HoldPostSeconds;
        HoldModeEnabled = s.HoldModeEnabled; // last — triggers OnHoldModeEnabledChanged

        // Apply saved language (must be before status strings and theme)
        var lang = s.Language;
        if (!AvailableLanguages.Contains(lang)) lang = AvailableLanguages.FirstOrDefault() ?? "ru";
        Loc.Load(lang);
        SelectedLanguage = lang;

        // Apply theme: auto-detect from Windows on first launch, then use user's choice
        _themeSetByUser = s.ThemeSetByUser;
        SelectedThemeIndex = s.ThemeSetByUser
            ? (s.Theme is "Dark" or "Тёмная" ? 1 : 0)
            : DetectWindowsTheme();
        _settingsLoaded = true;

        // Init status strings after localization is loaded
        ObsStatus = Loc.T("loc_StatusObsDisconnected");
        RecordingStatus = Loc.T("loc_StatusReady");
    }

    public void SaveSettings()
    {
        var s = new AppSettings
        {
            ObsHost = ObsHost,
            ObsPort = ObsPort,
            ObsPassword = string.IsNullOrEmpty(ObsPassword) ? null : ObsPassword,
            OutputRootDirectory = OutputRootDirectory,
            PreSeconds = PreSeconds,
            PostSeconds = PostSeconds,
            AudioCodec = AudioCodec,
            AudioBitrate = AudioBitrate,
            WhisperModel = WhisperModel,
            TranscriptionLanguage = TranscriptionLanguage,
            Glossary = Glossary,
            GlossaryFilePath = GlossaryFilePath,
            AutoStartObs = AutoStartObs,
            ObsExePath = ObsExePath,
            StartWithWindows = StartWithWindows,
            MinimizeToTray = MinimizeToTray,
            Theme = SelectedThemeIndex == 1 ? "Dark" : "Light",
            ThemeSetByUser = _themeSetByUser,
            Hotkeys = HotkeyBindings.Select(h => new HotkeyBindingData
            {
                Action = h.Action,
                Key = (int)h.Key,
                Modifiers = (int)h.Modifiers
            }).ToList(),
            MaxHistoryCount = MaxHistoryCount,
            DeleteFilesOnClear = DeleteFilesOnClear,
            ClearMarkersOnVideoLoad = ClearMarkersOnVideoLoad,
            UseCustomVideoPath = UseCustomVideoPath,
            CustomVideoPath = CustomVideoPath,
            VideoPathCopy = VideoPathCopy,
            UseCustomAudioPath = UseCustomAudioPath,
            CustomAudioPath = CustomAudioPath,
            AudioPathCopy = AudioPathCopy,
            UseCustomTxtPath = UseCustomTxtPath,
            CustomTxtPath = CustomTxtPath,
            TxtPathCopy = TxtPathCopy,
            UseCustomTablePath = UseCustomTablePath,
            CustomTablePath = CustomTablePath,
            TablePathCopy = TablePathCopy,
            AskSessionName = AskSessionName,
            AppendDateSuffix = AppendDateSuffix,
            DateSuffixFormat = DateSuffixFormat,
            HoldModeEnabled = HoldModeEnabled,
            HoldPreSeconds = HoldPreSeconds,
            HoldPostSeconds = HoldPostSeconds,
            SessionHistory = SessionHistory.ToList(),
            Language = SelectedLanguage
        };
        _settingsService.Save(s);
    }

    private AppSettings CreateSettingsSnapshot() => new()
    {
        ObsHost = ObsHost,
        ObsPort = ObsPort,
        OutputRootDirectory = OutputRootDirectory,
        PreSeconds = PreSeconds,
        PostSeconds = PostSeconds,
        AudioCodec = AudioCodec,
        AudioBitrate = AudioBitrate,
        WhisperModel = WhisperModel,
        TranscriptionLanguage = TranscriptionLanguage,
        Glossary = Glossary,
        GlossaryFilePath = GlossaryFilePath,
        HoldModeEnabled = HoldModeEnabled,
        HoldPreSeconds = HoldPreSeconds,
        HoldPostSeconds = HoldPostSeconds,
        UseCustomVideoPath = UseCustomVideoPath,
        CustomVideoPath = CustomVideoPath,
        VideoPathCopy = VideoPathCopy,
        UseCustomAudioPath = UseCustomAudioPath,
        CustomAudioPath = CustomAudioPath,
        AudioPathCopy = AudioPathCopy,
        UseCustomTxtPath = UseCustomTxtPath,
        CustomTxtPath = CustomTxtPath,
        TxtPathCopy = TxtPathCopy,
        UseCustomTablePath = UseCustomTablePath,
        CustomTablePath = CustomTablePath,
        TablePathCopy = TablePathCopy
    };

    public void InitializeHotkeys(Window window)
    {
        _hotkeyService.Initialize(window);
        _hotkeyService.RegisterHotkeys(HotkeyBindings);
    }

    public void RefreshHotkeys()
    {
        _hotkeyService.RegisterHotkeys(HotkeyBindings);
    }

    // --- Commands ---

    [RelayCommand]
    private async Task TestObsConnectionAsync()
    {
        ObsStatus = Loc.T("loc_StatusObsConnecting");
        var pw = string.IsNullOrEmpty(ObsPassword) ? null : ObsPassword;
        var ok = await _obs.ConnectAsync(ObsHost, ObsPort, pw);
        ObsConnected = ok;
        ObsStatus = ok ? Loc.T("loc_StatusObsConnected") : Loc.T("loc_StatusObsFailed");
        if (ok) SaveSettings();
    }

    [RelayCommand]
    private void BrowseOutputDirectory()
    {
        var dialog = new Microsoft.Win32.OpenFolderDialog
        {
            Title = Loc.T("loc_DlgOutputDir")
        };
        if (dialog.ShowDialog() == true)
        {
            OutputRootDirectory = dialog.FolderName;
            SaveSettings();
        }
    }

    [RelayCommand]
    private void BrowseGlossaryFile()
    {
        var dialog = new Microsoft.Win32.OpenFileDialog
        {
            Title = Loc.T("loc_DlgGlossary"),
            Filter = Loc.T("loc_FilterGlossary")
        };
        if (dialog.ShowDialog() == true)
        {
            GlossaryFilePath = dialog.FileName;
            SaveSettings();
        }
    }

    [RelayCommand]
    private void ClearHistory()
    {
        if (DeleteFilesOnClear)
        {
            foreach (var entry in SessionHistory)
            {
                try
                {
                    if (Directory.Exists(entry.FolderPath))
                        Directory.Delete(entry.FolderPath, true);
                }
                catch (Exception ex) { LogSvc.Warn($"ClearHistory delete failed: {ex.Message}"); }
            }
        }
        SessionHistory.Clear();
        SaveSettings();
    }

    [RelayCommand]
    private void BrowseObsExe()
    {
        var dialog = new Microsoft.Win32.OpenFileDialog
        {
            Title = Loc.T("loc_DlgObsExe"),
            Filter = Loc.T("loc_FilterObsExe")
        };
        if (dialog.ShowDialog() == true)
        {
            ObsExePath = dialog.FileName;
            SaveSettings();
        }
    }

    [RelayCommand]
    private async Task StartRecordingAsync()
    {
        if (!ObsConnected)
        {
            RecordingStatus = Loc.T("loc_StatusNeedObs");
            return;
        }

        if (string.IsNullOrWhiteSpace(OutputRootDirectory))
        {
            RecordingStatus = Loc.T("loc_StatusNeedOutputDir");
            return;
        }

        try
        {
            // Resolve session name (без запроса — пользователь может задать имя перед экспортом)
            var nameToUse = SessionName.Trim();
            _sessionNameWasAutoGenerated = string.IsNullOrEmpty(nameToUse);

            var now = DateTime.Now;
            var videoName = BuildVideoName(nameToUse, now);

            // Create session folder — named after the video file (includes date suffix if configured)
            var sessionDir = _sessionService.CreateSessionFolder(OutputRootDirectory, string.IsNullOrEmpty(videoName) ? null : videoName);
            _currentSession = new SessionData
            {
                SessionName = Path.GetFileName(sessionDir),
                SessionFolder = sessionDir,
                StartedAt = now,
                SettingsSnapshot = CreateSettingsSnapshot()
            };
            _currentSession.SettingsSnapshot.SessionVideoName = videoName;
            SetEffectiveDirs(_currentSession);

            // Set OBS record directory to effective video dir
            Directory.CreateDirectory(_currentSession.EffectiveVideoDir);
            await _obs.SetRecordDirectoryAsync(_currentSession.EffectiveVideoDir);

            // Start recording
            await _obs.StartRecordAsync();

            IsRecording = true;
            Markers.Clear();
            RecordingStatus = Loc.T("loc_StatusRecording");
            RecordingTime = "00:00:00";
            CurrentTab = 0;
            _recordingTimer.Start();
        }
        catch (Exception ex)
        {
            LogSvc.Error("StartRecording failed", ex);
            RecordingStatus = $"{Loc.T("loc_StatusError")}: {ex.Message}";
        }
    }

    [RelayCommand]
    private async Task StopRecordingAsync()
    {
        if (!IsRecording) return;

        try
        {
            RecordingStatus = Loc.T("loc_StatusStopping");
            var outputPath = await _obs.StopRecordAsync();
            _recordingTimer.Stop();
            IsRecording = false;

            if (_currentSession != null)
            {
                _currentSession.StoppedAt = DateTime.Now;
                _currentSession.ObsOutputPath = outputPath;
                _currentSession.Markers = Markers.ToList();

                // Move video file
                if (!string.IsNullOrEmpty(outputPath))
                {
                    RecordingStatus = Loc.T("loc_StatusMovingVideo");
                    var videoPath = await _sessionService.MoveVideoToSession(
                        outputPath, _currentSession.SessionFolder,
                        _currentSession.SettingsSnapshot.SessionVideoName,
                        _currentSession.EffectiveVideoDir);
                    _currentSession.VideoFilePath = videoPath;
                    CopyToCustomPaths(_currentSession); // copy video to custom path if copy mode
                }

                // Get duration
                if (_currentSession.VideoFilePath != null)
                {
                    var dur = await _ffmpeg.GetDurationAsync(_currentSession.VideoFilePath);
                    _currentSession.Duration = dur;
                }

                _sessionService.SaveSessionMeta(_currentSession);

                // Add to history
                var entry = new SessionHistoryEntry
                {
                    SessionName = _currentSession.SessionName,
                    FolderPath = _currentSession.SessionFolder,
                    CreatedAt = _currentSession.StartedAt,
                    MarkerCount = _currentSession.Markers.Count
                };
                SessionHistory.Insert(0, entry);
                SaveSettings();

                RecordingStatus = Loc.T("loc_StatusRecordingDone");
                ReviewReady = true;
                CurrentTab = 1; // Экспорт
            }
        }
        catch (Exception ex)
        {
            LogSvc.Error("StopRecording failed", ex);
            RecordingStatus = $"{Loc.T("loc_StatusError")}: {ex.Message}";
        }
    }

    [RelayCommand]
    private async Task LoadExistingVideoAsync()
    {
        if (string.IsNullOrWhiteSpace(OutputRootDirectory))
        {
            System.Windows.MessageBox.Show(
                Loc.T("loc_StatusNeedOutputDir2"),
                "ClipNotes",
                System.Windows.MessageBoxButton.OK,
                System.Windows.MessageBoxImage.Warning);
            CurrentTab = 3;
            return;
        }

        var dialog = new Microsoft.Win32.OpenFileDialog
        {
            Title = Loc.T("loc_DlgSelectVideo"),
            Filter = Loc.T("loc_FilterVideo")
        };

        if (dialog.ShowDialog() != true) return;

        try
        {
            var videoBaseName = Path.GetFileNameWithoutExtension(dialog.FileName);
            var sessionName = BuildVideoName(videoBaseName, DateTime.Now);
            var sessionDir = _sessionService.CreateSessionFolder(OutputRootDirectory, string.IsNullOrEmpty(sessionName) ? null : sessionName);
            _currentSession = new SessionData
            {
                SessionName = Path.GetFileName(sessionDir),
                SessionFolder = sessionDir,
                StartedAt = DateTime.Now,
                SettingsSnapshot = CreateSettingsSnapshot(),
                VideoFilePath = dialog.FileName
            };
            _currentSession.SettingsSnapshot.SessionVideoName = sessionName;
            SetEffectiveDirs(_currentSession);

            SetupToolPaths();
            ValidateTools();
            var dur = await _ffmpeg.GetDurationAsync(dialog.FileName);
            _currentSession.Duration = dur;

            LoadedVideoPath = dialog.FileName;
            if (ClearMarkersOnVideoLoad)
                Markers.Clear();
            ReviewReady = true;
            ProcessingStatus = $"{Loc.T("loc_StatusVideoLoaded")}: {Path.GetFileName(dialog.FileName)} ({dur:hh\\:mm\\:ss})";
            CurrentTab = 1;
        }
        catch (Exception ex)
        {
            LogSvc.Error("LoadExistingVideo failed", ex);
            ProcessingStatus = $"{Loc.T("loc_StatusError")}: {ex.Message}";
        }
    }

    [RelayCommand]
    private void AddManualMarker()
    {
        if (_currentSession == null)
        {
            ProcessingStatus = Loc.T("loc_StatusNeedVideo");
            return;
        }

        if (!TimeSpan.TryParseExact(ManualMarkerTimecode, @"hh\:mm\:ss", null, out var ts) &&
            !TimeSpan.TryParseExact(ManualMarkerTimecode, @"h\:mm\:ss", null, out ts) &&
            !TimeSpan.TryParseExact(ManualMarkerTimecode, @"mm\:ss", null, out ts))
        {
            ProcessingStatus = Loc.T("loc_StatusBadTimecode");
            return;
        }

        var marker = new Marker
        {
            Index = Markers.Count + 1,
            Type = ManualMarkerType,
            Timestamp = ts,
            Timecode = ts.ToString(@"hh\:mm\:ss")
        };

        Markers.Add(marker);
        ManualMarkerTimecode = (ts + TimeSpan.FromSeconds(30)).ToString(@"hh\:mm\:ss");
        SaveMarkersToSession();
    }

    [RelayCommand]
    private void RemoveMarker(Marker? marker)
    {
        if (marker == null) return;
        Markers.Remove(marker);
        // Re-index
        for (int i = 0; i < Markers.Count; i++)
            Markers[i].Index = i + 1;
        SaveMarkersToSession();
    }

    [RelayCommand]
    private void ImportMarkers()
    {
        var dialog = new Microsoft.Win32.OpenFileDialog
        {
            Title = Loc.T("loc_DlgImportMarkers"),
            Filter = Loc.T("loc_FilterMarkers")
        };
        if (dialog.ShowDialog() != true) return;

        var file = _sessionService.LoadMarkersFile(dialog.FileName);
        if (file == null || file.Markers.Count == 0)
        {
            ProcessingStatus = Loc.T("loc_StatusMarkersEmpty");
            return;
        }

        foreach (var entry in file.Markers)
        {
            if (!Enum.TryParse<MarkerType>(entry.Type, true, out var markerType)) continue;
            if (!TimeSpan.TryParse(entry.Timestamp, out var ts)) continue;

            TimeSpan? holdDuration = null;
            if (!string.IsNullOrEmpty(entry.HoldDuration) && TimeSpan.TryParse(entry.HoldDuration, out var hd))
                holdDuration = hd;

            Markers.Add(new Marker
            {
                Index = Markers.Count + 1,
                Type = markerType,
                Timestamp = ts,
                Timecode = ts.ToString(@"hh\:mm\:ss"),
                Text = entry.Text,
                GenerateAudio = entry.GenerateAudio,
                GenerateText = entry.GenerateText,
                HoldDuration = holdDuration
            });
        }
        ProcessingStatus = $"{Loc.T("loc_StatusImported")}: {file.Markers.Count}";
        SaveMarkersToSession();
    }

    private void SetEffectiveDirs(SessionData session)
    {
        var s = session.SettingsSnapshot;
        var sf = session.SessionFolder;
        // Copy mode: generate to default session folder first, then copy to custom path after pipeline
        session.EffectiveVideoDir = s.UseCustomVideoPath && !string.IsNullOrWhiteSpace(s.CustomVideoPath) && !s.VideoPathCopy
            ? s.CustomVideoPath : Path.Combine(sf, "video");
        session.EffectiveAudioDir = s.UseCustomAudioPath && !string.IsNullOrWhiteSpace(s.CustomAudioPath) && !s.AudioPathCopy
            ? s.CustomAudioPath : Path.Combine(sf, "audio");
        session.EffectiveTxtDir = s.UseCustomTxtPath && !string.IsNullOrWhiteSpace(s.CustomTxtPath) && !s.TxtPathCopy
            ? s.CustomTxtPath : Path.Combine(sf, "txt");
        session.EffectiveTableDir = s.UseCustomTablePath && !string.IsNullOrWhiteSpace(s.CustomTablePath) && !s.TablePathCopy
            ? s.CustomTablePath : Path.Combine(sf, "table");
    }

    private static void CopyToCustomPaths(SessionData session)
    {
        var s = session.SettingsSnapshot;
        var sf = session.SessionFolder;

        if (s.UseCustomVideoPath && !string.IsNullOrWhiteSpace(s.CustomVideoPath) && s.VideoPathCopy
            && session.VideoFilePath != null && File.Exists(session.VideoFilePath))
        {
            Directory.CreateDirectory(s.CustomVideoPath);
            File.Copy(session.VideoFilePath,
                Path.Combine(s.CustomVideoPath, Path.GetFileName(session.VideoFilePath)), overwrite: true);
        }

        if (s.UseCustomAudioPath && !string.IsNullOrWhiteSpace(s.CustomAudioPath) && s.AudioPathCopy)
        {
            var src = Path.Combine(sf, "audio");
            if (Directory.Exists(src))
            {
                Directory.CreateDirectory(s.CustomAudioPath);
                foreach (var f in Directory.GetFiles(src))
                    if (!Path.GetFileName(f).Equals("master.wav", StringComparison.OrdinalIgnoreCase))
                        File.Copy(f, Path.Combine(s.CustomAudioPath, Path.GetFileName(f)), overwrite: true);
            }
        }

        if (s.UseCustomTxtPath && !string.IsNullOrWhiteSpace(s.CustomTxtPath) && s.TxtPathCopy)
        {
            var src = Path.Combine(sf, "txt");
            if (Directory.Exists(src))
            {
                Directory.CreateDirectory(s.CustomTxtPath);
                foreach (var f in Directory.GetFiles(src, "*.txt"))
                    File.Copy(f, Path.Combine(s.CustomTxtPath, Path.GetFileName(f)), overwrite: true);
            }
        }

        if (s.UseCustomTablePath && !string.IsNullOrWhiteSpace(s.CustomTablePath) && s.TablePathCopy)
        {
            var src = Path.Combine(sf, "table", "ClipNotes.xlsx");
            if (File.Exists(src))
            {
                Directory.CreateDirectory(s.CustomTablePath);
                File.Copy(src, Path.Combine(s.CustomTablePath, "ClipNotes.xlsx"), overwrite: true);
            }
        }
    }

    private string BuildVideoName(string baseName, DateTime dt)
    {
        if (!AppendDateSuffix || string.IsNullOrWhiteSpace(DateSuffixFormat))
            return baseName;
        var suffix = DateSuffixFormat
            .Replace("{yyyy}", dt.Year.ToString("D4"))
            .Replace("{yy}", dt.ToString("yy"))
            .Replace("{mm}", dt.Month.ToString("D2"))
            .Replace("{dd}", dt.Day.ToString("D2"))
            .Replace("{HH}", dt.Hour.ToString("D2"))
            .Replace("{ss}", dt.Second.ToString("D2"));
        return string.IsNullOrWhiteSpace(baseName) ? suffix : $"{baseName}{suffix}";
    }

    private void SaveMarkersToSession()
    {
        if (_currentSession == null) return;
        _sessionService.SaveMarkersFile(_currentSession.SessionFolder, Markers);
    }

    [RelayCommand]
    private async Task AddMarkerAsync(MarkerType type)
    {
        if (!IsRecording || _currentSession == null) return;

        try
        {
            var status = await _obs.GetRecordStatusAsync();
            if (status == null) return;

            var marker = new Marker
            {
                Index = Markers.Count + 1,
                Type = type,
                Timestamp = status.Value.duration,
                Timecode = status.Value.timecode.Length > 8
                    ? status.Value.timecode[..8]
                    : status.Value.timecode
            };

            Application.Current?.Dispatcher.Invoke(() =>
            {
                Markers.Add(marker);
                SaveMarkersToSession();
            });
        }
        catch (Exception ex)
        {
            LogSvc.Error("AddMarker failed", ex);
            RecordingStatus = $"{Loc.T("loc_StatusError")}: {ex.Message}";
        }
    }

    [RelayCommand]
    private async Task GenerateAsync()
    {
        if (_currentSession == null) return;
        if (IsProcessing) return;

        if (string.IsNullOrEmpty(_currentSession.VideoFilePath) || !File.Exists(_currentSession.VideoFilePath))
        {
            ProcessingStatus = Loc.T("loc_StatusNeedVideo");
            return;
        }

        // Спросить имя сессии перед генерацией, если оно не было задано при записи
        if (AskSessionName && _sessionNameWasAutoGenerated)
        {
            var input = InputDialog.Show(Loc.T("loc_DlgSessionName"), Loc.T("loc_DlgSessionNamePrompt"), "");
            if (input == null) return; // пользователь отменил
            var userProvidedName = input.Trim();
            if (!string.IsNullOrEmpty(userProvidedName))
            {
                _currentSession.SessionName = userProvidedName;
                SessionName = userProvidedName;
                _sessionNameWasAutoGenerated = false;
            }
        }

        IsProcessing = true;
        ProcessingStatus = Loc.T("loc_StatusProcessing");
        ProcessingProgress = 0;
        _pipelineCts = new CancellationTokenSource();

        try
        {
            SetupToolPaths();
            _currentSession.Markers = Markers.ToList();

            var pipeline = new PipelineService(_ffmpeg, _whisper, _excel);
            pipeline.StatusChanged += s =>
                Application.Current?.Dispatcher.Invoke(() => ProcessingStatus = s);
            pipeline.ProgressChanged += (current, total) =>
                Application.Current?.Dispatcher.Invoke(() =>
                {
                    ProcessingProgress = current;
                    ProcessingTotal = total;
                });

            await pipeline.RunAsync(_currentSession, _pipelineCts.Token);
            CopyToCustomPaths(_currentSession);

            ProcessingStatus = Loc.T("loc_StatusProcessingDone");
        }
        catch (OperationCanceledException)
        {
            ProcessingStatus = Loc.T("loc_StatusCancelled");
        }
        catch (Exception ex)
        {
            LogSvc.Error("Generation pipeline failed", ex);
            var msg = ex.Message.Length > 300 ? ex.Message[..300] + "…" : ex.Message;
            ProcessingStatus = $"{Loc.T("loc_StatusError")}: {msg}";
        }
        finally
        {
            IsProcessing = false;
        }
    }

    [RelayCommand]
    private void CancelGeneration()
    {
        _pipelineCts?.Cancel();
    }

    [RelayCommand]
    private void OpenSessionFolder()
    {
        var folder = _currentSession?.SessionFolder;
        if (!string.IsNullOrEmpty(folder) && Directory.Exists(folder))
            Process.Start("explorer.exe", folder);
    }

    [RelayCommand]
    private void OpenHistoryFolder(string? folderPath)
    {
        if (!string.IsNullOrEmpty(folderPath) && Directory.Exists(folderPath))
            Process.Start("explorer.exe", folderPath);
    }

    private async void OnRecordingTimerTick(object? sender, EventArgs e)
    {
        if (!IsRecording) return;
        try
        {
            var status = await _obs.GetRecordStatusAsync();
            if (status != null)
                RecordingTime = status.Value.timecode.Length > 8
                    ? status.Value.timecode[..8]
                    : status.Value.timecode;
        }
        catch { }
    }

    private void OnRecordStateChanged(string state)
    {
        Application.Current.Dispatcher.Invoke(() =>
        {
            RecordingStatus = state switch
            {
                "OBS_WEBSOCKET_OUTPUT_STARTING" => Loc.T("loc_StatusObsStarting"),
                "OBS_WEBSOCKET_OUTPUT_STARTED"  => Loc.T("loc_StatusRecording"),
                "OBS_WEBSOCKET_OUTPUT_STOPPING" => Loc.T("loc_StatusObsStopping"),
                "OBS_WEBSOCKET_OUTPUT_STOPPED"  => Loc.T("loc_StatusObsStopped"),
                _ => state
            };
        });
    }

    private void OnRecordStopped(string outputPath)
    {
        // Handled via StopRecordingAsync
    }

    private async Task StartHoldAsync(MarkerType type)
    {
        var status = await _obs.GetRecordStatusAsync();
        if (status == null) return;
        _holdStart = status.Value.duration;
        _holdMarkerType = type;
        _holdStartWallClock = DateTime.Now;
        IsHolding = true;
        HoldingType = type;
        HoldingTimerText = "0.0";
        _holdTimer.Start();
        RecordingStatus = $"{Loc.T("loc_StatusHolding")}: {type} @ {_holdStart:hh\\:mm\\:ss}";
    }

    private async Task EndHoldAsync()
    {
        _holdTimer.Stop();
        IsHolding = false;
        if (_holdStart == null) return;
        try
        {
            var status = await _obs.GetRecordStatusAsync();
            if (status == null) return;

            var holdEnd = status.Value.duration;
            var holdDuration = holdEnd - _holdStart.Value;
            if (holdDuration < TimeSpan.Zero) holdDuration = TimeSpan.Zero;

            var marker = new Marker
            {
                Index = Markers.Count + 1,
                Type = _holdMarkerType,
                Timestamp = _holdStart.Value,
                Timecode = _holdStart.Value.ToString(@"hh\:mm\:ss"),
                HoldDuration = holdDuration
            };

            Markers.Add(marker);
            SaveMarkersToSession();
            RecordingStatus = $"[{_holdMarkerType}] {marker.TimestampFormatted} ({holdDuration:mm\\:ss})";
        }
        finally
        {
            _holdStart = null;
        }
    }

    public async Task StartUiHoldAsync(MarkerType type)
    {
        if (!HoldModeEnabled || !IsRecording || _currentSession == null || _holdStart != null) return;
        await StartHoldAsync(type);
    }

    public async Task EndUiHoldAsync()
    {
        if (!IsHolding || _currentSession == null) return;
        await EndHoldAsync();
    }

    private void OnHotkeyPressed(HotkeyAction action)
    {
        Application.Current.Dispatcher.Invoke(async () =>
        {
            var isMarkerAction = action is HotkeyAction.MarkerBug or HotkeyAction.MarkerTask or HotkeyAction.MarkerNote or HotkeyAction.MarkerSummary;

            if (isMarkerAction && HoldModeEnabled && IsRecording && _currentSession != null)
            {
                _holdMarkerType = action switch
                {
                    HotkeyAction.MarkerBug => MarkerType.Bug,
                    HotkeyAction.MarkerTask => MarkerType.Task,
                    HotkeyAction.MarkerSummary => MarkerType.Summary,
                    _ => MarkerType.Note
                };
                await StartHoldAsync(_holdMarkerType);
                return;
            }

            switch (action)
            {
                case HotkeyAction.MarkerBug:
                    await AddMarkerAsync(MarkerType.Bug);
                    break;
                case HotkeyAction.MarkerTask:
                    await AddMarkerAsync(MarkerType.Task);
                    break;
                case HotkeyAction.MarkerNote:
                    await AddMarkerAsync(MarkerType.Note);
                    break;
                case HotkeyAction.MarkerSummary:
                    await AddMarkerAsync(MarkerType.Summary);
                    break;
                case HotkeyAction.StartRecording:
                    await StartRecordingAsync();
                    break;
                case HotkeyAction.StopRecording:
                    await StopRecordingAsync();
                    break;
                case HotkeyAction.Generate:
                    await GenerateAsync();
                    break;
                case HotkeyAction.OpenOutputFolder:
                    OpenSessionFolder();
                    break;
            }
        });
    }

    private void OnHotkeyReleased(HotkeyAction action)
    {
        if (!HoldModeEnabled || !IsRecording || _currentSession == null || _holdStart == null) return;
        Application.Current.Dispatcher.Invoke(async () => await EndHoldAsync());
    }

    [RelayCommand]
    private void BrowseCustomPath(string which)
    {
        using var dialog = new System.Windows.Forms.FolderBrowserDialog { Description = Loc.T("loc_DlgSelectFolder") };
        if (dialog.ShowDialog() != System.Windows.Forms.DialogResult.OK) return;
        switch (which)
        {
            case "video": CustomVideoPath = dialog.SelectedPath; break;
            case "audio": CustomAudioPath = dialog.SelectedPath; break;
            case "txt":   CustomTxtPath   = dialog.SelectedPath; break;
            case "table": CustomTablePath = dialog.SelectedPath; break;
        }
    }

    private void OnLogEntryAdded(string line)
    {
        Application.Current?.Dispatcher.Invoke(() =>
            LogText = string.IsNullOrEmpty(LogText) ? line : LogText + "\n" + line);
    }

    [RelayCommand]
    private void OpenLogsFolder()
    {
        try
        {
            Directory.CreateDirectory(LogSvc.LogDir);
            Process.Start(new ProcessStartInfo(LogSvc.LogDir) { UseShellExecute = true });
        }
        catch (Exception ex) { LogSvc.Error("OpenLogsFolder failed", ex); }
    }

    [RelayCommand]
    private void CopyLogsToClipboard()
    {
        try { System.Windows.Clipboard.SetText(string.IsNullOrEmpty(LogText) ? "" : LogText); }
        catch (Exception ex) { LogSvc.Error("CopyLogsToClipboard failed", ex); }
    }

    public void Cleanup()
    {
        LogSvc.LogEntryAdded -= OnLogEntryAdded;
        _recordingTimer.Stop();
        _hotkeyService.Dispose();
        _obs.Dispose();
        SaveSettings();
    }
}

public record ModelOption(string Value, string Display)
{
    public override string ToString() => Display;
    public string ModelName => Display.Contains(" — ") ? Display[..Display.IndexOf(" — ")] : Display;
    public string VramHint  => Display.Contains(" — ") ? Display[(Display.IndexOf(" — ") + 3)..] : "";
}
