using System.IO;
using System.Windows;
using ClipNotes.Helpers;
using ClipNotes.Models;
using ClipNotes.Services;
using CommunityToolkit.Mvvm.Input;
using LogSvc = ClipNotes.Services.LogService;
using Loc = ClipNotes.Helpers.LocalizationService;

namespace ClipNotes.ViewModels;

public partial class MainViewModel
{
    [RelayCommand]
    private async Task LoadExistingVideoAsync()
    {
        if (string.IsNullOrWhiteSpace(OutputRootDirectory))
        {
            MessageBox.Show(
                Loc.T("loc_StatusNeedOutputDir2"),
                "ClipNotes",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            CurrentTab = 3;
            return;
        }

        var dialog = new Microsoft.Win32.OpenFileDialog
        {
            Title = Loc.T("loc_DlgSelectVideo"),
            Filter = Loc.T("loc_FilterVideo")
        };

        if (dialog.ShowDialog() != true) return;

        try
        {
            var videoBaseName = Path.GetFileNameWithoutExtension(dialog.FileName);
            var sessionName = BuildVideoName(videoBaseName, DateTime.Now);
            var sessionDir = _sessionService.CreateSessionFolder(OutputRootDirectory, string.IsNullOrEmpty(sessionName) ? null : sessionName);
            _currentSession = new SessionData
            {
                SessionName = Path.GetFileName(sessionDir),
                SessionFolder = sessionDir,
                StartedAt = DateTime.Now,
                SettingsSnapshot = CreateSettingsSnapshot(),
                VideoFilePath = dialog.FileName
            };
            _currentSession.SettingsSnapshot.SessionVideoName = sessionName;
            SetEffectiveDirs(_currentSession);

            SetupToolPaths();
            ValidateTools();
            var dur = await _ffmpeg.GetDurationAsync(dialog.FileName);
            _currentSession.Duration = dur;

            LoadedVideoPath = dialog.FileName;
            if (ClearMarkersOnVideoLoad)
                Markers.Clear();
            ReviewReady = true;
            ProcessingStatus = $"{Loc.T("loc_StatusVideoLoaded")}: {Path.GetFileName(dialog.FileName)} ({dur:hh\\:mm\\:ss})";
            CurrentTab = 1;
        }
        catch (Exception ex)
        {
            LogSvc.Error("LoadExistingVideo failed", ex);
            ProcessingStatus = $"{Loc.T("loc_StatusError")}: {ex.Message}";
        }
    }

    [RelayCommand]
    private async Task GenerateAsync()
    {
        if (_currentSession == null) return;
        if (IsProcessing) return;

        if (string.IsNullOrEmpty(_currentSession.VideoFilePath) || !File.Exists(_currentSession.VideoFilePath))
        {
            ProcessingStatus = Loc.T("loc_StatusNeedVideo");
            return;
        }

        // Спросить имя сессии перед генерацией, если оно не было задано при записи
        if (AskSessionName && _sessionNameWasAutoGenerated)
        {
            var input = InputDialog.Show(Loc.T("loc_DlgSessionName"), Loc.T("loc_DlgSessionNamePrompt"), "");
            if (input == null) return; // пользователь отменил
            var userProvidedName = input.Trim();
            if (!string.IsNullOrEmpty(userProvidedName))
            {
                _currentSession.SessionName = userProvidedName;
                SessionName = userProvidedName;
                _sessionNameWasAutoGenerated = false;
            }
        }

        IsProcessing = true;
        ProcessingStatus = Loc.T("loc_StatusProcessing");
        ProcessingProgress = 0;
        _pipelineCts = new CancellationTokenSource();

        try
        {
            SetupToolPaths();
            _currentSession.Markers = Markers.ToList();

            var pipeline = new PipelineService(_ffmpeg, _whisper, _excel, _sessionService);
            pipeline.StatusChanged += s =>
                Application.Current?.Dispatcher.Invoke(() => ProcessingStatus = s);
            pipeline.ProgressChanged += (current, total) =>
                Application.Current?.Dispatcher.Invoke(() =>
                {
                    ProcessingProgress = current;
                    ProcessingTotal = total;
                });

            await pipeline.RunAsync(_currentSession, _pipelineCts.Token);
            CopyToCustomPaths(_currentSession);

            ProcessingStatus = Loc.T("loc_StatusProcessingDone");
        }
        catch (OperationCanceledException)
        {
            ProcessingStatus = Loc.T("loc_StatusCancelled");
        }
        catch (Exception ex)
        {
            LogSvc.Error("Generation pipeline failed", ex);
            var msg = ex.Message.Length > 300 ? ex.Message[..300] + "…" : ex.Message;
            ProcessingStatus = $"{Loc.T("loc_StatusError")}: {msg}";
        }
        finally
        {
            IsProcessing = false;
        }
    }

    [RelayCommand]
    private void CancelGeneration()
    {
        _pipelineCts?.Cancel();
    }

    private static void CopyToCustomPaths(SessionData session)
    {
        var s = session.SettingsSnapshot;
        var sf = session.SessionFolder;

        if (s.UseCustomVideoPath && !string.IsNullOrWhiteSpace(s.CustomVideoPath) && s.VideoPathCopy
            && session.VideoFilePath != null && File.Exists(session.VideoFilePath))
        {
            Directory.CreateDirectory(s.CustomVideoPath);
            File.Copy(session.VideoFilePath,
                Path.Combine(s.CustomVideoPath, Path.GetFileName(session.VideoFilePath)), overwrite: true);
        }

        if (s.UseCustomAudioPath && !string.IsNullOrWhiteSpace(s.CustomAudioPath) && s.AudioPathCopy)
        {
            var src = Path.Combine(sf, "audio");
            if (Directory.Exists(src))
            {
                Directory.CreateDirectory(s.CustomAudioPath);
                foreach (var f in Directory.GetFiles(src))
                    if (!Path.GetFileName(f).Equals("master.wav", StringComparison.OrdinalIgnoreCase))
                        File.Copy(f, Path.Combine(s.CustomAudioPath, Path.GetFileName(f)), overwrite: true);
            }
        }

        if (s.UseCustomTxtPath && !string.IsNullOrWhiteSpace(s.CustomTxtPath) && s.TxtPathCopy)
        {
            var src = Path.Combine(sf, "txt");
            if (Directory.Exists(src))
            {
                Directory.CreateDirectory(s.CustomTxtPath);
                foreach (var f in Directory.GetFiles(src, "*.txt"))
                    File.Copy(f, Path.Combine(s.CustomTxtPath, Path.GetFileName(f)), overwrite: true);
            }
        }

        if (s.UseCustomTablePath && !string.IsNullOrWhiteSpace(s.CustomTablePath) && s.TablePathCopy)
        {
            var src = Path.Combine(sf, "table", "ClipNotes.xlsx");
            if (File.Exists(src))
            {
                Directory.CreateDirectory(s.CustomTablePath);
                File.Copy(src, Path.Combine(s.CustomTablePath, "ClipNotes.xlsx"), overwrite: true);
            }
        }
    }
}
