using System.IO;
using System.Windows;
using System.Windows.Threading;
using ClipNotes.Helpers;
using ClipNotes.Models;
using ClipNotes.Services;
using CommunityToolkit.Mvvm.Input;
using LogSvc = ClipNotes.Services.LogService;
using Loc = ClipNotes.Helpers.LocalizationService;

namespace ClipNotes.ViewModels;

public partial class MainViewModel
{
    public void InitializeHotkeys(Window window)
    {
        _hotkeyService.Initialize(window);
        _hotkeyService.RegisterHotkeys(HotkeyBindings);
    }

    public void RefreshHotkeys()
    {
        _hotkeyService.RegisterHotkeys(HotkeyBindings);
    }

    [RelayCommand]
    private async Task StartRecordingAsync()
    {
        if (!ObsConnected)
        {
            RecordingStatus = Loc.T("loc_StatusNeedObs");
            return;
        }

        if (string.IsNullOrWhiteSpace(OutputRootDirectory))
        {
            RecordingStatus = Loc.T("loc_StatusNeedOutputDir");
            return;
        }

        try
        {
            // Resolve session name (без запроса — пользователь может задать имя перед экспортом)
            var nameToUse = SessionName.Trim();
            _sessionNameWasAutoGenerated = string.IsNullOrEmpty(nameToUse);

            var now = DateTime.Now;
            var videoName = BuildVideoName(nameToUse, now);

            // Create session folder — named after the video file (includes date suffix if configured)
            var sessionDir = _sessionService.CreateSessionFolder(OutputRootDirectory, string.IsNullOrEmpty(videoName) ? null : videoName);
            _currentSession = new SessionData
            {
                SessionName = Path.GetFileName(sessionDir),
                SessionFolder = sessionDir,
                StartedAt = now,
                SettingsSnapshot = CreateSettingsSnapshot()
            };
            _currentSession.SettingsSnapshot.SessionVideoName = videoName;
            SetEffectiveDirs(_currentSession);

            // Set OBS record directory to effective video dir
            Directory.CreateDirectory(_currentSession.EffectiveVideoDir);
            await _obs.SetRecordDirectoryAsync(_currentSession.EffectiveVideoDir);

            // Start recording
            await _obs.StartRecordAsync();

            IsRecording = true;
            Markers.Clear();
            RecordingStatus = Loc.T("loc_StatusRecording");
            RecordingTime = "00:00:00";
            CurrentTab = 0;
            _recordingTimer.Start();
        }
        catch (Exception ex)
        {
            LogSvc.Error("StartRecording failed", ex);
            RecordingStatus = $"{Loc.T("loc_StatusError")}: {ex.Message}";
        }
    }

    [RelayCommand]
    private async Task StopRecordingAsync()
    {
        if (!IsRecording) return;

        try
        {
            RecordingStatus = Loc.T("loc_StatusStopping");
            var outputPath = await _obs.StopRecordAsync();
            _recordingTimer.Stop();
            IsRecording = false;

            if (_currentSession != null)
            {
                _currentSession.StoppedAt = DateTime.Now;
                _currentSession.ObsOutputPath = outputPath;
                _currentSession.Markers = Markers.ToList();

                // Move video file — validate path from OBS to prevent UNC/traversal exploitation.
                if (!string.IsNullOrEmpty(outputPath) && IsLocalPath(outputPath))
                {
                    RecordingStatus = Loc.T("loc_StatusMovingVideo");
                    var videoPath = await _sessionService.MoveVideoToSession(
                        outputPath, _currentSession.SessionFolder,
                        _currentSession.SettingsSnapshot.SessionVideoName,
                        _currentSession.EffectiveVideoDir);
                    _currentSession.VideoFilePath = videoPath;
                    CopyToCustomPaths(_currentSession); // copy video to custom path if copy mode
                }
                else if (!string.IsNullOrEmpty(outputPath))
                {
                    LogSvc.Warn($"StopRecording: OBS returned non-local output path '{outputPath}', ignoring.");
                }

                // Get duration
                if (_currentSession.VideoFilePath != null)
                {
                    var dur = await _ffmpeg.GetDurationAsync(_currentSession.VideoFilePath);
                    _currentSession.Duration = dur;
                }

                _sessionService.SaveSessionMeta(_currentSession);

                // Add to history
                var entry = new SessionHistoryEntry
                {
                    SessionName = _currentSession.SessionName,
                    FolderPath = _currentSession.SessionFolder,
                    CreatedAt = _currentSession.StartedAt,
                    MarkerCount = _currentSession.Markers.Count
                };
                SessionHistory.Insert(0, entry);
                SaveSettings();

                RecordingStatus = Loc.T("loc_StatusRecordingDone");
                ReviewReady = true;
                CurrentTab = 1; // Экспорт
            }
        }
        catch (Exception ex)
        {
            LogSvc.Error("StopRecording failed", ex);
            RecordingStatus = $"{Loc.T("loc_StatusError")}: {ex.Message}";
        }
    }

    [RelayCommand]
    private async Task AddMarkerAsync(MarkerType type)
    {
        if (!IsRecording || _currentSession == null) return;

        try
        {
            var status = await _obs.GetRecordStatusAsync();
            if (status == null) return;

            var marker = new Marker
            {
                Index = Markers.Count + 1,
                Type = type,
                Timestamp = status.Value.duration,
                Timecode = status.Value.timecode.Length > 8
                    ? status.Value.timecode[..8]
                    : status.Value.timecode
            };

            Application.Current?.Dispatcher.Invoke(() =>
            {
                Markers.Add(marker);
                SaveMarkersToSession();
            });
        }
        catch (Exception ex)
        {
            LogSvc.Error("AddMarker failed", ex);
            RecordingStatus = $"{Loc.T("loc_StatusError")}: {ex.Message}";
        }
    }

    [RelayCommand]
    private void AddManualMarker()
    {
        if (_currentSession == null)
        {
            ProcessingStatus = Loc.T("loc_StatusNeedVideo");
            return;
        }

        if (!TimeSpan.TryParseExact(ManualMarkerTimecode, @"hh\:mm\:ss", null, out var ts) &&
            !TimeSpan.TryParseExact(ManualMarkerTimecode, @"h\:mm\:ss", null, out ts) &&
            !TimeSpan.TryParseExact(ManualMarkerTimecode, @"mm\:ss", null, out ts))
        {
            ProcessingStatus = Loc.T("loc_StatusBadTimecode");
            return;
        }

        var marker = new Marker
        {
            Index = Markers.Count + 1,
            Type = ManualMarkerType,
            Timestamp = ts,
            Timecode = ts.ToString(@"hh\:mm\:ss")
        };

        Markers.Add(marker);
        ManualMarkerTimecode = (ts + TimeSpan.FromSeconds(30)).ToString(@"hh\:mm\:ss");
        SaveMarkersToSession();
    }

    [RelayCommand]
    private void RemoveMarker(Marker? marker)
    {
        if (marker == null) return;
        Markers.Remove(marker);
        // Re-index
        for (int i = 0; i < Markers.Count; i++)
            Markers[i].Index = i + 1;
        SaveMarkersToSession();
    }

    [RelayCommand]
    private void ImportMarkers()
    {
        var dialog = new Microsoft.Win32.OpenFileDialog
        {
            Title = Loc.T("loc_DlgImportMarkers"),
            Filter = Loc.T("loc_FilterMarkers")
        };
        if (dialog.ShowDialog() != true) return;

        var file = _sessionService.LoadMarkersFile(dialog.FileName);
        if (file == null || file.Markers.Count == 0)
        {
            ProcessingStatus = Loc.T("loc_StatusMarkersEmpty");
            return;
        }

        const int MaxImportMarkers = 10_000;
        if (file.Markers.Count > MaxImportMarkers)
        {
            ProcessingStatus = $"Файл содержит слишком много маркеров: {file.Markers.Count} (максимум {MaxImportMarkers})";
            return;
        }

        foreach (var entry in file.Markers)
        {
            if (!Enum.TryParse<MarkerType>(entry.Type, true, out var markerType)) continue;
            if (!TimeSpan.TryParse(entry.Timestamp, out var ts)) continue;

            TimeSpan? holdDuration = null;
            if (!string.IsNullOrEmpty(entry.HoldDuration) && TimeSpan.TryParse(entry.HoldDuration, out var hd))
                holdDuration = hd;

            Markers.Add(new Marker
            {
                Index = Markers.Count + 1,
                Type = markerType,
                Timestamp = ts,
                Timecode = ts.ToString(@"hh\:mm\:ss"),
                Text = entry.Text,
                GenerateAudio = entry.GenerateAudio,
                GenerateText = entry.GenerateText,
                HoldDuration = holdDuration
            });
        }
        ProcessingStatus = $"{Loc.T("loc_StatusImported")}: {file.Markers.Count}";
        SaveMarkersToSession();
    }

    private void SaveMarkersToSession()
    {
        if (_currentSession == null) return;
        _sessionService.SaveMarkersFile(_currentSession.SessionFolder, Markers);
    }

    private string BuildVideoName(string baseName, DateTime dt)
    {
        if (!AppendDateSuffix || string.IsNullOrWhiteSpace(DateSuffixFormat))
            return baseName;
        var suffix = DateSuffixFormat
            .Replace("{yyyy}", dt.Year.ToString("D4"))
            .Replace("{yy}", dt.ToString("yy"))
            .Replace("{mm}", dt.Month.ToString("D2"))
            .Replace("{dd}", dt.Day.ToString("D2"))
            .Replace("{HH}", dt.Hour.ToString("D2"))
            .Replace("{ss}", dt.Second.ToString("D2"));
        return string.IsNullOrWhiteSpace(baseName) ? suffix : $"{baseName}{suffix}";
    }

    private void SetEffectiveDirs(SessionData session)
    {
        var s = session.SettingsSnapshot;
        var sf = session.SessionFolder;
        // Copy mode: generate to default session folder first, then copy to custom path after pipeline
        session.EffectiveVideoDir = s.UseCustomVideoPath && !string.IsNullOrWhiteSpace(s.CustomVideoPath) && !s.VideoPathCopy
            ? s.CustomVideoPath : Path.Combine(sf, "video");
        session.EffectiveAudioDir = s.UseCustomAudioPath && !string.IsNullOrWhiteSpace(s.CustomAudioPath) && !s.AudioPathCopy
            ? s.CustomAudioPath : Path.Combine(sf, "audio");
        session.EffectiveTxtDir = s.UseCustomTxtPath && !string.IsNullOrWhiteSpace(s.CustomTxtPath) && !s.TxtPathCopy
            ? s.CustomTxtPath : Path.Combine(sf, "txt");
        session.EffectiveTableDir = s.UseCustomTablePath && !string.IsNullOrWhiteSpace(s.CustomTablePath) && !s.TablePathCopy
            ? s.CustomTablePath : Path.Combine(sf, "table");
    }

    private void OnRecordStateChanged(string state)
    {
        Application.Current.Dispatcher.Invoke(() =>
        {
            RecordingStatus = state switch
            {
                "OBS_WEBSOCKET_OUTPUT_STARTING" => Loc.T("loc_StatusObsStarting"),
                "OBS_WEBSOCKET_OUTPUT_STARTED"  => Loc.T("loc_StatusRecording"),
                "OBS_WEBSOCKET_OUTPUT_STOPPING" => Loc.T("loc_StatusObsStopping"),
                "OBS_WEBSOCKET_OUTPUT_STOPPED"  => Loc.T("loc_StatusObsStopped"),
                _ => state
            };
        });
    }

    private void OnRecordStopped(string outputPath)
    {
        // Handled via StopRecordingAsync
    }

    private async void OnRecordingTimerTick(object? sender, EventArgs e)
    {
        if (!IsRecording) return;
        try
        {
            var status = await _obs.GetRecordStatusAsync();
            if (status != null)
                RecordingTime = status.Value.timecode.Length > 8
                    ? status.Value.timecode[..8]
                    : status.Value.timecode;
        }
        catch (Exception) { } // Transient OBS polling failure — ignore
    }
}
